// <auto-generated />
using System;
using AppService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230330083759_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("AppService.Tables.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AuthorBookId")
                        .HasColumnType("int");

                    b.Property<int?>("EditorialId")
                        .HasColumnType("int");

                    b.Property<string>("NameBook")
                        .HasColumnType("longtext");

                    b.Property<bool?>("OnlineAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("PagesCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("TypeBook")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorBookId");

                    b.HasIndex("EditorialId");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("AppService.Tables.Enterprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Rut")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Enterprise");
                });

            modelBuilder.Entity("AppService.Tables.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Rut")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("AppService.Tables.Book", b =>
                {
                    b.HasOne("AppService.Tables.Person", "AuthorBook")
                        .WithMany()
                        .HasForeignKey("AuthorBookId");

                    b.HasOne("AppService.Tables.Enterprise", "Editorial")
                        .WithMany()
                        .HasForeignKey("EditorialId");

                    b.Navigation("AuthorBook");

                    b.Navigation("Editorial");
                });
#pragma warning restore 612, 618
        }
    }
}
